[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_blackjack = "CapEG2CccYXmkf3n4MDA77UfcyMKYVwfNHb5k9DtuyNt"

[programs.devnet]
solana_blackjack = "CapEG2CccYXmkf3n4MDA77UfcyMKYVwfNHb5k9DtuyNt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/nico/new-kpr.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
