[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_blackjack = "7LstZ1Mn48VJDjUvzWvZW5XssULqdYsP6wyU1ACGeD4E"

[programs.devnet]
solana_blackjack = "7LstZ1Mn48VJDjUvzWvZW5XssULqdYsP6wyU1ACGeD4E"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/nico/new-kpr.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
